name: "Check Branch Commits"
description: |
  Runs the branch commit checker on aptos-core, assuming it is already checked out in the current working directory.
  The branch commit checker verifies the following:
    - That all commits in devnet, testnet and mainnet, are in main.
    - That all commits in testnet are in devnet.
    - That all commits in mainnet are in testnet.
  These rules will help to ensure we're rolling forward appropriately, i.e., main -> devnet -> testnet -> mainnet.
inputs:
  TIMEOUT_MINUTES:
    description: "The number of minutes to wait for branch commit checking to finish."
    required: true

runs:
  using: composite
  steps:
    - name: Install Dependencies
      shell: bash
      run: |
        echo "${HOME}/bin/" >> $GITHUB_PATH # default INSTALL_DIR to path
    - name: Run branch commit checker
      shell: bash
      run: |
        source "$HOME/.cargo/env" # Required for allowing python access to cargo
        pip install -r ${{ github.action_path }}/requirements.txt
        timeout "${{ inputs.TIMEOUT_MINUTES }}m" python3 ${{ github.action_path }}/check_branch_commits.py
