# This workflow ensures that aptos-core branches do
# not have inconsistent commits.

name: "check-branch-commits"
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0,12 * * *" # At hour 0 and 12 - AKA twice a day (UTC)
  pull_request:
    paths:
      - ".github/workflows/check-branch-commits.yaml"

jobs:
  check-branch-commits:
    timeout-minutes: 60 # Run for at most 1 hour
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # pin@v3

      - uses: ./.github/actions/check-branch-commits
        with:
          TIMEOUT_MINUTES: 60 # Run for at most 1 hour

      - name: Post to a Slack channel on failure
        if: failure()
        id: slack
        uses: slackapi/slack-github-action@936158bbe252e9a6062e793ea4609642c966e302 # pin@v1.21.0
        with:
          payload: |
            {
              "text": "${{ ':x:' }} `${{ github.job }}`: <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|link>"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.FORGE_SLACK_WEBHOOK_URL }}
