name: Continuous E2E Nft Mint Test

permissions:
  issues: write
  pull-requests: write

on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * *"

jobs:
  ### Please remember to use different namespace for different tests
  # Performance test in an optimal setting
  run-forge-nft-mint-test:
    uses: aptos-labs/aptos-core/.github/workflows/workflow-run-forge.yaml@main
    secrets: inherit
    with:
      FORGE_NAMESPACE: forge-nft-mint-test
      FORGE_RUNNER_DURATION_SECS: 900
      FORGE_TEST_SUITE: nft_mint
      POST_TO_SLACK: true
