# This defines a workflow to replay transactions on the given chain with the latest aptos node software.
# In order to trigger it go to the Actions Tab of the Repo, click "replay-verify" and then "Run Workflow".
#
# On PR, a single test case will run. On workflow_dispatch, you may specify the CHAIN_NAME to verify.

name: "replay-verify"
on:
  # Allow triggering manually
  workflow_dispatch:
    inputs:
      GIT_SHA:
        required: false
        type: string
        description: The git SHA1 to test. If not specified, it will use the latest commit on main.
      CHAIN_NAME:
        required: false
        type: choice
        options: [testnet, mainnet, all]
        default: all
        description: The chain name to test. If not specified, it will test both testnet and mainnet.
  pull_request:
    paths:
      - ".github/workflows/replay-verify.yaml"
      - "testsuite/replay-verify.py"
  schedule:
    - cron: "0 8,20 * * *"

# cancel redundant builds
concurrency:
  # cancel redundant builds on PRs (only on PR, not on branches)
  group: ${{ github.workflow }}-${{ (github.event_name == 'pull_request' && github.ref) || github.sha }}
  cancel-in-progress: true

jobs:
  replay-testnet:
    if: ${{ github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' && inputs.CHAIN_NAME == 'testnet' || inputs.CHAIN_NAME == 'all' }}
    uses: aptos-labs/aptos-core/.github/workflows/workflow-run-replay-verify.yaml@main
    secrets: inherit
    with:
      GIT_SHA: ${{ inputs.GIT_SHA }}
      # replay-verify config
      BUCKET: aptos-testnet-backup-2223d95b
      SUB_DIR: e1
      HISTORY_START: 250000000 # TODO: We need an exhaustive list of txns_to_skip before we can set this to 0.
      TXNS_TO_SKIP: 46874937 151020059 409163615 409163669 409163708 409163774 409163845 409163955 409164059 409164191 414625832
      BACKUP_CONFIG_TEMPLATE_PATH: terraform/helm/fullnode/files/backup/s3-public.yaml
      # workflow config
      RUNS_ON: "high-perf-docker-with-local-ssd"
      TIMEOUT_MINUTES: 720

  replay-mainnet:
    if: ${{ github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' && inputs.CHAIN_NAME == 'testnet' || inputs.CHAIN_NAME == 'all' }}
    uses: aptos-labs/aptos-core/.github/workflows/workflow-run-replay-verify.yaml@main
    secrets: inherit
    with:
      GIT_SHA: ${{ inputs.GIT_SHA }}
      # replay-verify config
      BUCKET: aptos-mainnet-backup-backup-831a69a8
      SUB_DIR: e1
      HISTORY_START: 0
      TXNS_TO_SKIP: 12253479 12277499
      BACKUP_CONFIG_TEMPLATE_PATH: terraform/helm/fullnode/files/backup/s3-public.yaml
      # workflow config
      RUNS_ON: "high-perf-docker-with-local-ssd"
      TIMEOUT_MINUTES: 720

  test-replay:
    if: ${{ github.event_name == 'pull_request' }}
    uses: aptos-labs/aptos-core/.github/workflows/workflow-run-replay-verify.yaml@main
    with:
      GIT_SHA: ${{ github.event.pull_request.head.sha }}
      # replay-verify config
      BUCKET: aptos-testnet-backup-2223d95b
      SUB_DIR: e1
      HISTORY_START: 250000000 # TODO: We need an exhaustive list of txns_to_skip before we can set this to 0.
      TXNS_TO_SKIP: 46874937 151020059 409163615 409163669 409163708 409163774 409163845 409163955 409164059 409164191 414625832
      BACKUP_CONFIG_TEMPLATE_PATH: terraform/helm/fullnode/files/backup/s3-public.yaml
      # workflow config
      RUNS_ON: "high-perf-docker-with-local-ssd"
      TIMEOUT_MINUTES: 20
