name: Continuous E2E Release Test

permissions:
  issues: write
  pull-requests: write

on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * *"

jobs:
  # Run a faster chaos forge to quickly surface correctness failures
  run-release-blocking-forge:
    uses: aptos-labs/aptos-core/.github/workflows/workflow-run-forge.yaml@main
    secrets: inherit
    with:
      # Run for 5 hours unless its on a pr
      FORGE_RUNNER_DURATION_SECS: ${{ github.event_name == 'pull_request' && 300 || 18000 }}
      FORGE_ENABLE_HAPROXY: true
      FORGE_TEST_SUITE: land_blocking
      # Give us 12 hour timeout
      TIMEOUT_MINUTES: 720
