# This workflow runs a public fullnode using the `mainnet` branch,
# connects the public fullnode to `mainnet` and synchronizes the
# node using fast syncing to verify that nothing has been broken.

name: "fullnode-fast-mainnet-stable"
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0,12 * * *" # At hour 0 and 12 - aka twice a day (UTC)
  pull_request:
    paths:
      - ".github/workflows/fullnode-fast-mainnet-stable.yaml"

jobs:
  fullnode-fast-mainnet-stable:
    uses: ./.github/workflows/run-fullnode-sync.yaml
    secrets: inherit
    with:
      TEST_NAME: fullnode-fast-mainnet-stable
      BRANCH: mainnet
      NETWORK: mainnet
      BOOTSTRAPPING_MODE: DownloadLatestStates
      CONTINUOUS_SYNCING_MODE: ExecuteTransactions
