# This workflow is a simple wrapper around the fullnode-sync github
# action. It invokes the action with all the neccessary configurations
# required by the specific fullnode sync test instance.

name: "Run Fullnode Sync"

on:
  workflow_call:
    inputs:
      TEST_NAME:
        description: "The unique name of the fullnode test."
        type: string
        required: true
      BRANCH:
        description: "The aptos-core branch to switch to before running the fullnode."
        type: string
        required: true
      NETWORK:
        description: "The network to connect the fullnode to: devnet, testnet, or mainnet."
        type: string
        required: true
      BOOTSTRAPPING_MODE:
        description: "The state sync bootstrapping mode for the fullnode."
        type: string
        required: true
      CONTINUOUS_SYNCING_MODE:
        description: "The state sync continuous syncing mode for the fullnode."
        type: string
        required: true
      TIMEOUT_MINUTES:
        description: "The number of minutes to wait for fullnode sync to finish."
        type: number
        required: false
        default: 300 # Run for at most 5 hours

jobs:
  fullnode-sync:
    runs-on: medium-perf-docker-with-local-ssd
    timeout-minutes: ${{ inputs.TIMEOUT_MINUTES }}
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # pin@v3

      - uses: ./.github/actions/fullnode-sync
        with:
          TIMEOUT_MINUTES: ${{ inputs.TIMEOUT_MINUTES }}
          BRANCH: ${{ inputs.BRANCH }}
          NETWORK: ${{ inputs.NETWORK }}
          BOOTSTRAPPING_MODE: ${{ inputs.BOOTSTRAPPING_MODE }}
          CONTINUOUS_SYNCING_MODE: ${{ inputs.CONTINUOUS_SYNCING_MODE }}
          DATA_DIR_FILE_PATH: /tmp/
          NODE_LOG_FILE_PATH: /tmp/node_log

      - name: Upload node logs as an artifact
        uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: node_log
          path: |
            /tmp/node_log
          retention-days: 14

      - name: Post to a Slack channel on failure
        if: failure()
        id: slack
        uses: slackapi/slack-github-action@936158bbe252e9a6062e793ea4609642c966e302 # pin@v1.21.0
        with:
          payload: |
            {
              "text": "${{ ':x:' }} `${{ inputs.TEST_NAME  }}`: <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|link>"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.FORGE_SLACK_WEBHOOK_URL }}

      # Because we have to checkout the actions and then check out a different
      # branch, it's possible the actions directory will be modified. So, we
      # need to check it out again for the Post Run actions/checkout to succeed.
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # pin@v3
        with:
          path: actions
