[package]
name = "aptos-indexer-grpc-utils"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
cloud-storage = { workspace = true }
futures-util = { workspace = true }
redis = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
